envs:
  default:
    enabled: True

    notbit:
      useTor: False
      listenPort: 8444

      process:
        nice: 19

      objects:
        # Purge objects directory before starting notbit
        purgeAllOnStartup: False
        purgeOlderThan:
          onStartup: False
          periodic: False
          hours: 96

    bmCoreContacts:
      - name: 'galacteek-support'
        address: 'BM-87UhSBhPjGqENCxQerGXpxRfSZHs2aX3TKc'
        group: 'galacteek'

      - name: 'cipres'
        address: 'BM-87dtCqLxqnpwzUyjzL8etxGK8MQQrhnxnt1'
        group: 'galacteek'

    messages:
      welcome:
        subject: 'BitMessage is easy'
        body: >
          Your BitMessage identity has been generated. Your address is:

          **{bmAddress}**

          Be sure to [check the manual](manual:/messenger.html) for more
          information.

    mdirWatcher:
      # Settings for notbit's maildir watcher task
      sleepInterval: 60
