envs:
  default:
    styles:
      webEngine:
        sakura:
          '@type': 'QtWebEngineStyle'

          styleName: 'sakura'
          displayName:
            en: 'sakura'

          src: 'qrc:/share/styles/sakura/sakura.css'

        sakura-dark:
          '@type': 'QtWebEngineStyle'

          styleName: 'sakura-dark'
          displayName:
            en: 'sakura-dark'

          src: 'qrc:/share/styles/sakura-dark/sakura-dark.css'
