envs:
  default:
    qtWebEngine:
      numRasterThreads: 8

      ignoreGpuBlacklist: true
      enableGpuRasterization: true
      enableNativeGpuMemoryBuffers: true

      blink:
        darkMode: true
        darkModeContrast: 0.0
        darkModePagePolicy: 0
        darkModeImagePolicy: 0
        darkModeTextBrightnessThreshold: 150
        darkModeBackgroundBrightnessThreshold: 200
