graphEnvs:
  # Graphs definitions
  # ipg = interplanetary graph, g = galacteek
  beta:
    # Pubsub service config
    pubsub:
      heartbeat:
        intervalMin: 60
        intervalMax: 150

    # Graph synchronizers definitions
    synchronizers:
      urn:ipg:sync:xmlgzexport:
        type: rdfexport
        format: xml
        compression: gzip

      urn:ipg:sync:ttlgzexport:
        type: rdfexport
        format: ttl
        compression: gzip

      urn:ipg:sync:sparql1:
        type: sparql

      urn:ipg:sync:ontolochain1:
        type: ontolochain

    graphs:
      # Main graphs
      urn:ipg:g:c0:
        name: c0

        triplesRules:
          - subject: '^did:ipid:.*'
          - subject: '^i:/Person/'

      urn:ipg:g:c1:
        name: c1
      urn:ipg:g:h0:
        name: h0

        services:
          sparql:
            exportsAllow: true

          sync:
            use: 'urn:ipg:sync:ontolochain1'

      # Hashmarks (conjunctive)
      urn:ipg:g:hashmarks:
        name: hashmarks
        type: conjunctive

        namespace: 'urn:ipg:g:hashmarks'

        subgraphs:
          urn:ipg:g:hashmarks:main:
            name: hashmarks_main

        services:
          sparql:
            exportsAllow: true

          sync:
            use: 'urn:ipgsync:ttlgzexport'
