envs:
  default:
    publish:
      # Automatically republish local IPID
      autoRepublish: True

      # Republish delay (seconds)
      autoRepublishDelay: 300

      # IPNS publish values (local IPID)
      ipns:
        timeout: 300
        lifetime: '48h'
        ttl: '12h'

    resolve:
      # Timeout in seconds for resolving IPID documents
      timeout: 45

      cacheLifetime:
        # Default cache lifetime for IPIDs (in minutes)
        default:
          minutes: 10

        # Cache lifetime for local IPIDs (in minutes)
        local:
          minutes: 1036800

      # Delay before a resolved IPID is considered "stale", in seconds
      staleDelay: 180
