envs:
  default:
    resourceBlocker:
      enabled: false

      blockListsMasterUrl: ${gitlab_easy_asset_url:galacteek,dweb-blocklists,continuous-master,dweb-blocklists.yaml}

    services:
      g/core/peers/ident:
        psKeysListen:
          - 'g/services/app'
          - 'g/services'

    peers:
      limit: 2048
