envs:
  default:
    registries:
      icapsule-registry-gitlab-continuous:
        url: https://gitlab.com/galacteek/icapsule-registry/-/releases/continuous-${env:ICAPSULE_REGISTRY_BRANCH}/downloads/icapsule-registry.tar.gz
        enabled: True
        priority: 0

      icapsule-registry-local-dev:
        url: file:///${env:HOME}/icapsule-registry-dev.yaml
        enabled: False
        priority: 100

    profile:
      icapsulesByUri:
        urn:g:dapps:dvoz:
          install: latest
          autoload: true
